apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "polyaxon.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ template "polyaxon.fullname" . }}-config
{{ include "config.labels.common" . | indent 4 }}
{{ include "config.labels.roles.coreConfig" . | indent 4 }}
data:
  # Cluster
  POLYAXON_DEPLOYMENT_TYPE: {{ default "kubernetes" .Values.deploymentType | quote }}
  POLYAXON_PLATFORM_HOST: {{ template "config.platformHost" . }}
  POLYAXON_K8S_NAMESPACE: {{ .Release.Namespace | quote }}
  POLYAXON_K8S_APP_SECRET_NAME: {{ template "config.platformSecret" . }}
  POLYAXON_LOG_LEVEL: {{ default "WARNING" .Values.logLevel | quote }}
  POLYAXON_ENVIRONMENT: {{ default "production" .Values.environment | quote }}
  POLYAXON_TIME_ZONE: {{ .Values.timezone | quote }}
  # Versions
  POLYAXON_CHART_VERSION: {{ .Chart.Version | quote }}
  {{- if .Values.includeChartRevision }}
  POLYAXON_CHART_REVISION: {{ .Release.Revision | quote }}
  {{- end }}
  # Security Context
  {{- if and .Values.securityContext.enabled }}
  POLYAXON_SECURITY_CONTEXT_USER: {{ .Values.securityContext.runAsUser | quote }}
  POLYAXON_SECURITY_CONTEXT_GROUP: {{ .Values.securityContext.runAsGroup | quote }}
  {{- end }}
