{{- if or .Values.agent.enabled (not .Values.organizationKey) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "polyaxon.fullname" . }}-agent-config
  labels:
    app.kubernetes.io/name: {{ template "polyaxon.fullname" . }}-agent-config
{{ include "config.labels.common" . | indent 4 }}
{{ include "config.labels.roles.coreConfig" . | indent 4 }}
data:
  POLYAXON_K8S_IN_CLUSTER: "true"
  POLYAXON_WATCH_CLUSTER: {{ .Values.agent.watchCluster | quote }}
  POLYAXON_SINGLE_NAMESPACE: "{{ include "config.singleNamespace" . }}"
  POLYAXON_ADDITIONAL_NAMESPACES: {{ toJson .Values.agent.additionalNamespaces | quote }}
  POLYAXON_SET_AGENT: "true"
  {{- if .Values.agent.instance }}
  POLYAXON_AGENT_INSTANCE: {{ .Values.agent.instance | quote }}
  {{- end }}
  {{- if .Values.artifactsStore }}
  POLYAXON_AGENT_ARTIFACTS_STORE: {{ toJson .Values.artifactsStore | quote }}
  {{- else }}
  POLYAXON_AGENT_ARTIFACTS_STORE: {{ toJson .Values.defaultArtifactsStore | quote }}
  {{- end }}
  {{- if .Values.connections }}
  POLYAXON_AGENT_CONNECTIONS: {{ toJson .Values.connections | quote }}
  {{- end }}
  POLYAXON_AGENT_SIDECAR: {{ toJson .Values.sidecar | quote }}
  POLYAXON_AGENT_INIT: {{ toJson .Values.init | quote }}
  POLYAXON_AGENT_CLEANER: {{ toJson .Values.cleaner | quote }}
  POLYAXON_AGENT_NOTIFIER: {{ toJson .Values.notifier | quote }}
  POLYAXON_AGENT_DEFAULT_SCHEDULING: {{ include "config.agent.scheduling" . | fromYaml | toJson | quote }}
  {{- if .Values.agent.imagePullSecrets }}
  POLYAXON_AGENT_DEFAULT_IMAGE_PULL_SECRETS: {{ toJson .Values.agent.imagePullSecrets | quote }}
  {{- else }}
  {{- if .Values.imagePullSecrets }}
  POLYAXON_AGENT_DEFAULT_IMAGE_PULL_SECRETS: {{ toJson .Values.imagePullSecrets | quote }}
  {{- end }}
  {{- end }}
  {{- if .Values.rbac.enabled }}
  POLYAXON_AGENT_RUNS_SA: {{ template "polyaxon.fullname" . }}-runs-sa
  {{- end }}
  {{- if .Values.agentSecret }}
  POLYAXON_AGENT_SECRET_NAME: {{ .Values.agentSecret | quote }}
  {{- else }}
  {{- if .Values.agent.token }}
  POLYAXON_AGENT_SECRET_NAME: {{ template "polyaxon.fullname" . }}-agent-secret
  {{- end }}
  {{- end }}
  {{- if .Values.agent.isReplica }}
  POLYAXON_AGENT_IS_REPLICA: {{ .Values.agent.isReplica | quote }}
  {{- end }}
  POLYAXON_ENABLE_STATUS_FINALIZERS: {{ .Values.agent.enableStatusFinalizers | quote }}
  POLYAXON_ENABLE_LOGS_FINALIZERS: {{ .Values.agent.enableLogsFinalizers | quote }}
  {{- if .Values.agent.enableHealthChecks }}
  POLYAXON_AGENT_ENABLE_HEALTH_CHECKS: {{ .Values.agent.enableHealthChecks | quote }}
  {{- end }}
  {{- if .Values.agent.executorRefreshInterval }}
  POLYAXON_AGENT_EXECUTOR_REFRESH_INTERVAL: {{ .Values.agent.executorRefreshInterval | quote }}
  {{- end }}
  {{- if .Values.operator.maxConcurrentReconciles }}
  POLYAXON_MAX_CONCURRENT_RECONCILES: {{ .Values.operator.maxConcurrentReconciles | quote }}
  {{- end }}
  {{- if .Values.operator.leaderElection }}
  POLYAXON_LEADER_ELECTION: {{ .Values.operator.leaderElection | quote }}
  {{- end }}
  POLYAXON_TFJOB_ENABLED: {{ .Values.operators.tfjob | quote }}
  POLYAXON_PYTORCH_JOB_ENABLED: {{ .Values.operators.pytorchjob | quote }}
  POLYAXON_PADDLE_JOB_ENABLED: {{ .Values.operators.paddlejob | quote }}
  POLYAXON_XGBOOST_JOB_ENABLED: {{ .Values.operators.xgbjob | quote }}
  POLYAXON_MXJOB_ENABLED: {{ .Values.operators.mxjob | quote }}
  POLYAXON_MPIJOB_ENABLED: {{ .Values.operators.mpijob | quote }}
  POLYAXON_SPARK_JOB_ENABLED: {{ .Values.operators.sparkjob | quote }}
  POLYAXON_DASK_JOB_ENABLED: {{ .Values.operators.daskjob | quote }}
  POLYAXON_RAY_JOB_ENABLED: {{ .Values.operators.rayjob | quote }}
  {{- if .Values.proxy.enabled }}
  POLYAXON_AGENT_USE_PROXY_ENV_VARS_IN_OPS: {{ .Values.proxy.useInOps | quote }}
  {{- end }}
{{- end }}
