{{- $singleNamespace := include "config.singleNamespace" . | trim | lower | eq "true" -}}
{{- if and .Values.rbac.enabled .Values.operator.enabled (not $singleNamespace) }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "polyaxon.fullname" . }}-operator-sa
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "polyaxon.fullname" . }}-operator-sa
{{ include "config.labels.common" . | indent 4 }}
{{ include "config.labels.roles.coreConfig" . | indent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "polyaxon.fullname" . }}-operator-clusterrole
  labels:
    app.kubernetes.io/name: {{ template "polyaxon.fullname" . }}-operator-clusterrole
{{ include "config.labels.common" . | indent 4 }}
{{ include "config.labels.roles.coreConfig" . | indent 4 }}
rules:
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods/status
  - services/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - polyaxon.com
  resources:
  - clusters
  - jobs
  - kfjobs
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - polyaxon.com
  resources:
  - clusters/finalizers
  - jobs/finalizers
  - kfjobs/finalizers
  - services/finalizers
  verbs:
  - update
- apiGroups:
  - polyaxon.com
  resources:
  - clusters/status
  - jobs/status
  - kfjobs/status
  - services/status
  verbs:
  - get
  - patch
  - update
{{- if .Values.operators.mpijob }}
- apiGroups:
  - kubeflow.org
  resources:
  - mpijobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubeflow.org
  resources:
  - mpijobs/status
  verbs:
  - get
  - patch
  - update
{{- end }}
{{- if .Values.operators.pytorchjob }}
- apiGroups:
  - kubeflow.org
  resources:
  - pytorchjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubeflow.org
  resources:
  - pytorchjobs/status
  verbs:
  - get
  - patch
  - update
{{- end }}
{{- if .Values.operators.tfjob }}
- apiGroups:
  - kubeflow.org
  resources:
  - tfjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubeflow.org
  resources:
  - tfjobs/status
  verbs:
  - get
  - patch
  - update
{{- end }}
{{- if .Values.operators.raycluster }}
- apiGroups:
  - ray.io
  resources:
  - rayclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ray.io
  resources:
  - rayclusters/status
  verbs:
  - get
  - patch
  - update
{{- end}}
{{- if .Values.operators.daskcluster }}
- apiGroups:
  - kubernetes.dask.org
  resources:
  - daskclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubernetes.dask.org
  resources:
  - daskclusters/status
  verbs:
  - get
  - patch
  - update
{{- end}}
{{- if .Values.istio.enabled }}
- apiGroups:
  - networking.istio.io
  resources:
  - destinationrules
  - virtualservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.istio.io
  resources:
  - destinationrules/status
  - networking.istio.io
  verbs:
  - get
  - patch
  - update
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "polyaxon.fullname" . }}-operator-clusterrole-binding
  labels:
    app.kubernetes.io/name: {{ template "polyaxon.fullname" . }}-operator-clusterrole-binding
{{ include "config.labels.common" . | indent 4 }}
{{ include "config.labels.roles.coreConfig" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "polyaxon.fullname" . }}-operator-clusterrole
subjects:
  - kind: ServiceAccount
    name: {{ template "polyaxon.fullname" . }}-operator-sa
    namespace: {{ .Release.Namespace }}
{{- end }}
