apiVersion: v2
description: An enterprise-grade open-source platform for building, training, and monitoring large scale deep learning applications.
name: polyaxon
version: 2.9.1
appVersion: 2.9.1
keywords:
  - deep learning
  - a.i.
  - machine learning
  - infrastructure
sources:
  - https://github.com/polyaxon
home: https://polyaxon.com
icon: https://raw.githubusercontent.com/polyaxon/polyaxon/master/artifacts/logo/logo-small.png
maintainers:
  - name: Polyaxon
    email: contact@polyaxon.com
    url: polyaxon.com
dependencies:
  - name: postgresql
    version: 15.5.35
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: rabbitmq
    version: 11.7.0
    repository: https://charts.bitnami.com/bitnami
    condition: rabbitmq.enabled
  - name: redis
    version: 20.1.5
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
